# Generated by Django 4.0.6 on 2022-08-04 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0005_meetup_date_meetup_organizer_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meetup',
            old_name='partiants',
            new_name='participants',
        ),
    ]
